apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: dev
  labels:
    name: hello-node
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: aks-hello-node
  type: LoadBalancer