#namespaces defined in separate yaml
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: dev
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: local-hello-node
  namespace: dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: local-hello-node
    spec:
      containers:
        - name: hello-node
          image: 'bnaya/tmp-test:v2'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: dev
  labels:
    name: hello-node
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: local-hello-node
  type: NodePort